USE [master]
GO

CREATE DATABASE [Ensek]
	CONTAINMENT = NONE
	ON PRIMARY
		(
			NAME = N'Ensek',
			FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Ensek_data.mdf',
			SIZE = 8192 KB,
			MAXSIZE = UNLIMITED,
			FILEGROWTH = 65536 KB
		)
	LOG ON
		(
			NAME = N'Ensek_log',
			FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Ensek_log.ldf',
			SIZE = 8192 KB,
			MAXSIZE = 2048 GB,
			FILEGROWTH = 65536 KB
		)
	WITH CATALOG_COLLATION = DATABASE_DEFAULT,
	LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	BEGIN
		EXEC [Ensek].[dbo].[sp_fulltext_database] @action = 'enable'
	END
GO

ALTER DATABASE [Ensek] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ensek] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ensek] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ensek] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ensek] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ensek] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ensek] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ensek] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ensek] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ensek] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ensek] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ensek] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ensek] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ensek] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ensek] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ensek] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ensek] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ensek] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ensek] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ensek] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ensek] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ensek] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ensek] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Ensek] SET  MULTI_USER 
GO

ALTER DATABASE [Ensek] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ensek] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ensek] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ensek] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ensek] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ensek] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ensek] SET QUERY_STORE = ON
GO

ALTER DATABASE [Ensek] SET QUERY_STORE
	(
		OPERATION_MODE = READ_WRITE,
		CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
		DATA_FLUSH_INTERVAL_SECONDS = 900,
		INTERVAL_LENGTH_MINUTES = 60,
		MAX_STORAGE_SIZE_MB = 1000,
		QUERY_CAPTURE_MODE = AUTO,
		SIZE_BASED_CLEANUP_MODE = AUTO,
		MAX_PLANS_PER_QUERY = 200,
		WAIT_STATS_CAPTURE_MODE = ON
	)
GO

ALTER DATABASE [Ensek] SET  READ_WRITE 
GO
